app/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app/posts/blueprint.py
from flask import Blueprint, render_template, redirect, url_for
from models import Post, Tag, User
from .forms import PostForm # noqa
from flask_login import login_required, current_user

from flask import request
from app import db


posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/profile')
@login_required
def profile():
    return render_template('posts/profile.html', name=current_user.name)


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        user_id = current_user.id

        try:
            post = Post(title=title, body=body, user_id=user_id)
            db.session.add(post)
            db.session.commit()
        except:
            print('Smth wrong')

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
@login_required
def index():

    q = request.args.get('q')
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', pages=pages)


@posts.route('/all-bloggers')
@login_required
def all_bloggers():

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    users = User.query.filter()

    pages = users.paginate(page=page, per_page=5)

    return render_template('posts/all_bloggers.html', pages=pages)


@posts.route('/blogger/<id>')
@login_required
def user_detail(id):
    user = User.query.filter(User.id==id).first()
    all_posts = user.posts
    return render_template('posts/user_detail.html', user=user, posts=all_posts)


@posts.route('/<slug>')
@login_required
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts.all()

    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/all_bloggers.html
{% extends 'base.html' %}

{% block title %}

    All bloggers

{% endblock %}

{% block content_title %}

    All bloggers

{% endblock %}

{% block content %}
    {% for blogger in pages.items %}
        <p>
            <a href="{{ url_for('posts.user_detail', id=blogger.id) }}">{{ blogger }}</a>
        </p>
    {% endfor%}

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li {% if not pages.has_prev %} class="disabled" {% endif %}><a class="page-link" href="./?page={{ pages.prev_num }}">Previous</a></li>

        {% for page in pages.iter_pages() %}
            <li {% if page == pages.page %} class="active" {% endif %}><a class="page-link" href="./?page={{ page }}">{{ page }}</a></li>
        {% endfor %}

        <li {% if not pages.has_next %} class="disabled" {% endif %}><a class="page-link" href="./?page={{ pages.next_num }}">Next</a></li>
      </ul>
    </nav>

{% endblock %}

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  Create new post
{% endblock %}

{% block content_title %}
  New post
{% endblock %}

{% block content %}

  <div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">

      {% for field in form %}
        <div class="form-group">
          {{ field.label(class='control-label') }}
          {{ field(class='form-control') }}
        </div>
      {% endfor %}

      <br><button type="submit" class="btn btn-success">Create</button>

    </form>
  </div>

{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
  Edit post
{% endblock %}

{% block content_title %}
  Edit post
{% endblock %}

{% block content %}

  <div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">

      {% for field in form %}
        <div class="form-group">
          {{ field.label(class='control-label') }}
          {{ field(class='form-control') }}
        </div>
      {% endfor %}

      <br><button type="submit" class="btn btn-success">Edit</button>

    </form>
  </div>

{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}

    Posts

{% endblock %}

{% block content_title %}

    Posts

{% endblock %}

{% block content %}
    {% for post in pages.items %}
        <p>
            <a href="{{ url_for('posts.post_detail', slug=post.slug)}}">{{ post.title }}</a>
        </p>
    {% endfor%}

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li {% if not pages.has_prev %} class="disabled" {% endif %}><a class="page-link" href="./?page={{ pages.prev_num }}">Previous</a></li>

        {% for page in pages.iter_pages() %}
            <li {% if page == pages.page %} class="active" {% endif %}><a class="page-link" href="./?page={{ page }}">{{ page }}</a></li>
        {% endfor %}

        <li {% if not pages.has_next %} class="disabled" {% endif %}><a class="page-link" href="./?page={{ pages.next_num }}">Next</a></li>
      </ul>
    </nav>

{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block content_title %}
  {{ post.title }}
{% endblock %}

{% block content %}
  <div class="tags">
    {% for tag in tags %}
      <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge text-bg-primary">{{tag.name}}</span></a>
    {% endfor %}
  </div>

  <div class="main-content">
    {{ post.body }}
  </div>
{% endblock %}

app/posts/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Profile
{% endblock %}

{% block content_title %}
  Profile
{% endblock %}

{% block content %}
  <p>Welcome, {{ name }}!</p>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ tag.name }} posts
{% endblock %}

{% block content_title %}
  Post for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}

  {% for post in posts %}
    <div class="post">
      <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
    </div>
  {% endfor %}

{% endblock %}

app/posts/templates/posts/user_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ user.name }}
{% endblock %}

{% block content_title %}
  {{ user.name }}
{% endblock %}

{% block content %}
    {% for post in posts %}
      <p>
        <a href="{{ url_for('posts.post_detail', slug=post.slug)}}">{{ post.title }}</span></a>
      </p>
    {% endfor %}
{% endblock %}