app/models.py
from app import db
from datetime import datetime
import re
from flask_login import UserMixin


def slugify(string):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', string)


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'{self.name}'


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    posts = db.relationship('Post', backref='user', lazy='dynamic')

    def __str__(self):
        return f'{self.name}'

app/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate

from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_login import LoginManager


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)

from models import Post, Tag, User # noqa
admin = Admin(app)
admin.add_view(ModelView(Post, db.session))
admin.add_view(ModelView(Tag, db.session))
admin.add_view(ModelView(User, db.session))


login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main.py
from app import app
from app import db # noqa

from auth.blueprint import auth
from posts.blueprint import posts

import view # noqa

app.register_blueprint(auth)
app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

app/posts/blueprint.py
from flask import Blueprint, render_template, redirect, url_for
from models import Post, Tag, User
from .forms import PostForm # noqa
from flask_login import login_required, current_user

from flask import request
from app import db


posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/profile')
@login_required
def profile():
    return render_template('posts/profile.html', name=current_user.name)


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        user_id = current_user.id

        try:
            post = Post(title=title, body=body, user_id=user_id)
            db.session.add(post)
            db.session.commit()
        except:
            print('Smth wrong')

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
@login_required
def index():

    q = request.args.get('q')
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', pages=pages)


@posts.route('/all-bloggers')
@login_required
def all_bloggers():

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    users = User.query.filter()

    pages = users.paginate(page=page, per_page=5)

    return render_template('posts/all_bloggers.html', pages=pages)


@posts.route('/blogger/<id>')
@login_required
def user_detail(id):
    user = User.query.filter(User.id==id).first()
    all_posts = user.posts
    return render_template('posts/user_detail.html', user=user, posts=all_posts)


@posts.route('/<slug>')
@login_required
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts.all()

    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %} | Flask app
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index') }}">Blogger</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          {% if current_user.is_authenticated %}
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('posts.index') }}">All posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('posts.all_bloggers') }}">All bloggers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('posts.create_post') }}">Create post</a>
            </li>
          </ul>


          <form class="d-flex me-auto" role="search" method="GET">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
          {% endif %}

          <ul class="navbar-nav mb-2 mb-lg-0">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('posts.profile') }}">Profile</a>
                </li>
            {% endif %}
            {% if not current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('auth.signup') }}">Sign up</a>
            </li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <h1>
                {% block content_title %}

                {% endblock %}
            </h1>
            {% block content %}

            {% endblock %}
        </div>
    </div>


</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}

    Index page

{% endblock %}

{% block content_title %}

    Index page

{% endblock %}

{% block content %}

    content

{% endblock %}